### ISSUE TITLE
xcatprobe xcatmn usage errors in help menu

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#1725]
Few comments on xcatprobe: 
- The `-i` option is required , so it should not be surrounded by `[ ]` brackets which indicate optional argumnets... 
- replace `xcat` with `xCAT` to be consistent with the naming of the product.  

```
[root@c910f04x42vm20 ~]# xcatprobe xcatmn
Option -i is required                                                                                             [FAIL]
Usage:                                                                                                            
    xcatmn -h
    xcatmn [-i <install_nic>] [-V]  <---- indicates optional

Description:
    After xcat installation, use this command to check if xcat has been installed correctly and is ready for use.
    For hierarchical cluster, only the provision network on the same network as the management node is supported. If ...

Options:
    -h : Get usage information of xcatmn
    -V : Output more information for debug
    -i : Required. Specify the network interface name of provision network on management node

```

**Comment by whowutwut** [comment]
I'm ok to move this to 2.12.3..

**Comment by hu-weihua** [comment]
I fixed this bug by PR #2071 .

**Comment by whowutwut** [comment]
@hu-weihua  I ran this on the RC1 build today, it seems like the help message changes but nothing blocks if the `-i` option is not specified.. 

```
[root@fs4 yum.repos.d]# xcatprobe xcatmn 
<mn>: All xCAT deamons are running                                                                                [ OK ]
...
```

**Comment by whowutwut** [comment]
In addition, when I run the command with `-i` specified.. .seems like the command hangs forever. 

```
[root@fs4 yum.repos.d]# xcatprobe xcatmn -i enP4p1s0f2
<mn>: All xCAT deamons are running                                                                                [ OK ]
<mn>: xcatd can receive command request                                                                           [ OK ]
<mn>: 'site' table is configured correctly                                                                        [ OK ]
<mn>: Provision network is configured correctly                                                                   [ OK ]
<mn>: 'passwd' table is configured correctly                                                                      [ OK ]
<mn>: Important directory is configured correctly                                                                 [ OK ]
<mn>: SELinux is disabled on current server                                                                       [ OK ]
<mn>: HTTP service works well                                                                                     [ OK ]
<mn>: TFTP service works well                                                                                     [FAIL]

<waiting here for some time..never come back> 
^C

^C

^C^Z
[1]+  Stopped                 xcatprobe xcatmn -i enP4p1s0f2
[root@fs4 yum.repos.d]# ps -ef | grep xcatprobe
root     101131  97233  0 09:52 pts/15   00:00:00 perl /opt/xcat/bin/xcatprobe xcatmn -i enP4p1s0f2
root     101565  97233  0 09:55 pts/15   00:00:00 grep --color=auto xcatprobe
[root@fs4 yum.repos.d]# kill -9 101131
[root@fs4 yum.repos.d]# 
[1]+  Killed                  xcatprobe xcatmn -i enP4p1s0f2

```

**Comment by whowutwut** [comment]
@hu-weihua  There was some problems with this management node before, after  rebooting, it seems better...   
```
[root@fs4 autotest]# xcatprobe xcatmn -i enP4p1s0f2
<mn>: All xCAT deamons are running                                                                                [ OK ]
<mn>: xcatd can receive command request                                                                           [ OK ]
<mn>: 'site' table is configured correctly                                                                        [ OK ]
<mn>: Provision network is configured correctly                                                                   [ OK ]
<mn>: 'passwd' table is configured correctly                                                                      [ OK ]
<mn>: Important directory is configured correctly                                                                 [ OK ]
<mn>: SELinux is disabled on current server                                                                       [ OK ]
<mn>: HTTP service works well                                                                                     [ OK ]
<mn>: TFTP service works well                                                                                     [FAIL]
<mn>: TFTP check need 'tftp' tool, please install 'tftp' tool and try again                                       
<mn>: DHCP service works well                                                                                     [ OK ]
<mn>: Firewall is closed on current server                                                                        [ OK ]
<mn>: The disk space is enough for xCAT to work                                                                   [ OK ]
<mn>: The IP of master is a static IP address                                                                     [ OK ]
<mn>: The dhcpd.leases file is less than 100M                                                                     [ OK ]
======================do summary=====================                                                             
[MN]: Check on MN FAILED.                                                                                         [FAIL]
    TFTP service works well                                                                                       [FAIL]
        TFTP check need 'tftp' tool, please install 'tftp' tool and try again                                  
```
But there were things mounted and left in a strange state, so hopefully we recover OK out of xcatprobe. 

The first issue still exists, are we suppose to allow the user to execute without specifying the -i option?

**Comment by hu-weihua** [comment]
@whowutwut , I have add some check for option ``-i`` by pull request #2122 .

But I didn't get the point of your comment ``But there were things mounted and left in a strange state, so hopefully we recover OK out of xcatprobe. ``.  Could you tell me more about it? thanks

**Comment by whowutwut** [comment]
I think the test machine was left in a strange state so that xcatprobe has some problems running successfully. We rebooted the machine and things look better.   I don't think we need any action right now but it seems like xcatprobe will not recover OK when there are issues on the machine.  For example, that above comment shows it hangs forever.

**Comment by whowutwut** [comment]
I have verified with RC2 build today.
