### ISSUE TITLE
buildinfo file in the bz2 does not show correct VERSION for xCAT

### ISSUE THREAD

**Issue by whowutwut** [xcat2/xcat-core#2507]
Unless I'm downloading the incorrect file, the ``buildinfo`` is still using 2.13.1 ... should be 2.13.2...since it's the snap shot builds.  File is generated in buildcore.sh..  (and buildubuntu... )

```
[vhu@c910loginx01 tmp]$ wget http://xcat.org/files/xcat/xcat-core/2.13.x_Linux/core-snap/core-rpms-snap.tar.bz2
--2017-02-20 10:16:21--  http://xcat.org/files/xcat/xcat-core/2.13.x_Linux/core-snap/core-rpms-snap.tar.bz2
Resolving xcat.org... 166.70.135.166
Connecting to xcat.org|166.70.135.166|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4137135 (3.9M) [application/x-bzip2]
Saving to: “core-rpms-snap.tar.bz2”

100%[==========================================================>] 4,137,135   23.8M/s   in 0.2s

2017-02-20 10:16:21 (23.8 MB/s) - “core-rpms-snap.tar.bz2” saved [4137135/4137135]

[vhu@c910loginx01 tmp]$ tar -jxvf core-rpms-snap.tar.bz2  >> /dev/null
[vhu@c910loginx01 tmp]$ cat xcat-core/buildinfo
VERSION=2.13.1
RELEASE=snap201701130845
BUILD_TIME=Fri Jan 13 08:45:40 EST 2017
BUILD_MACHINE=c910f02c07p02
COMMIT_ID=6059a5c
```

@zet809  @tingtli  can we have someone look at this.   I'll try if I get a chance...  if there is no owner, then i'm not looking at it right now.

**Comment by tingtli** [comment]
@whowutwut  I think this is because the Version in 2.13 branch is still 2.13.1.
When we released 2.13.1, we ONLY update the master's Version file to 2.13.2, but not update Version file to 2.13.2 in 2.13 branch.
See Versions' log
On branch master
```
[root@c910f02c01p18 xcat-core]# git log Version
commit fc98911bc9e33afc1a17e2f7e28e6381f8ed5cfe
Author: zet809 <ertaozh@cn.ibm.com>
Date:   Fri Jan 13 16:57:35 2017 +0800

    Update Version

commit fd79f1c1ac82a3f63a876b6b1d72a99f418e2cd9
Author: litingt@cn.ibm.com <litingt@cn.ibm.com>
Date:   Fri Dec 9 01:52:57 2016 -0500

    update Version to 2.13.1
```
On 2.13 branch
```
  (use "git push" to publish your local commits)
[root@c910f02c01p18 xcat-core]# git log Version
commit fd79f1c1ac82a3f63a876b6b1d72a99f418e2cd9
Author: litingt@cn.ibm.com <litingt@cn.ibm.com>
Date:   Fri Dec 9 01:52:57 2016 -0500

    update Version to 2.13.1
```

**Comment by tingtli** [comment]
@whowutwut  Do you think this could be fixed?

**Comment by whowutwut** [comment]
Hi @tingtli  Thanks for looking at this.. 

I took the build on 2/20, when we started the RC1 build for 2.13.2.  The first merge of master -> 2.13 branch to create the RC build should have merged in the Version change.  right?  So why would we still have an old version file?

**Comment by whowutwut** [comment]
Ok, I looked at the RC1 build...  it was done 6 days ago... so looks like I didn't get the right snap build, I got the build from 1/13, not 2/20....   Let's close it.
