### ISSUE TITLE
xcatdb needs to be postgres

### ISSUE THREAD

**Issue by agibm** [xcat2/xcat-core#3938]
Compilation of messages of this issue:

somehow xcatdb installed as xqllite and the postboot scripts did not take us to postgres.

this is because this an early exit was in the script that was supposed to do the job.
we had not figured a way to make idempotent.

do it by hand for now.
pgsqlsetup -i -V

and now xcatd does not startup...
```
Sep 15 15:20:52 c699mgt00 xcatd[45235]: DBI connect('dbname=xcatdb;host=10.2.100.250','xcatadm',.....847.
Sep 15 15:20:52 c699mgt00 xcat[45237]: Could not connect to the database. Database handle not defined.
Sep 15 15:20:53 c699mgt00 xcatd[45235]: DBI connect('dbname=xcatdb;host=10.2.100.250','xcatadm',.....847.
Sep 15 15:20:53 c699mgt00 xcat[45237]: Could not connect to the database. Database handle not defined.
Sep 15 15:20:54 c699mgt00 xcatd[45235]: DBI connect('dbname=xcatdb;host=10.2.100.250','xcatadm',.....847.
Sep 15 15:20:54 c699mgt00 xcat[45237]: Could not connect to the database. Database handle not defined.
Sep 15 15:20:55 c699mgt00 xcatd[45235]: DBI connect('dbname=xcatdb;host=10.2.100.250','xcatadm',.....847.
Sep 15 15:20:55 c699mgt00 xcat[45237]: Could not connect to the database. Database handle not defined.
Sep 15 15:20:56 c699mgt00 xcatd[45235]: DBI connect('dbname=xcatdb;host=10.2.100.250','xcatadm',.....847.
Sep 15 15:20:56 c699mgt00 xcat[45237]: Could not connect to the database. Database handle not defined.
Hint: Some lines were ellipsized, use -l to show in full.
```
added to: /var/lib/pgsql/data/pg_hba.conf

host all all 10.2.100.17/32 md5

the interface for the xcat master is confined with an HA configuraiton:
```
[root@c699mgt00 ~]# ip a show dev enP1p12s0f2
4: enP1p12s0f2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN qlen 1000
link/ether 98:be:94:63🆎6e brd ff:ff:ff:ff:ff:ff
inet 10.2.100.17/16 brd 10.2.255.255 scope global enP1p12s0f2
valid_lft forever preferred_lft forever
inet 10.2.100.250/16 scope global secondary enP1p12s0f2:0
valid_lft forever preferred_lft forever
```
which look like caused this problem.

**Comment by whowutwut** [comment]
Cross link internal issue:https://github.ibm.com/DCS-research/WSC-coral/issues/34

**Comment by immarvin** [comment]
hi @agibm @whowutwut , this ticket  seems to be closed. so does it mean that this issue have been resolved?

**Comment by zet809** [comment]
Hi, @agibm , you shall also add line `host all all 10.2.100.250/32 md5` into the /var/lib/pgsql/data/pg_hba.conf file. Pls try and let us know the result. Thx!

**Comment by cxhong** [comment]
@zet809 , Ralph added that line to pg_hba.conf and also other modification.  He can able to recover the xCATdb at the end.  I think for this issue,  we need to verify how HA will work for xCATdb.

**Comment by ralphbellofatto** [comment]
yes, we already know that adding the values to the /var/lib/pgsql/data/pg_hba.conf by hand cleared the problem.

But then we had a postges db and NO data in the xcat DB.    We had to restore the xcat DB from backup by hand...


This problem should NOT have happened in the first place.

**Comment by whowutwut** [comment]
@immarvin The internal ticket was closed since @ralphbellofatto was able to resolve, but we still have an action item to figure out how to best handle this.. or why it happened in the first place, like Ralph says...

**Comment by zet809** [comment]
Pls reference issue #4067

**Comment by whowutwut** [comment]
@agibm  Can you update your real name in your GitHub profile, or msg me on Slack so that the xCAT team knows who you are in IBM...  I can't tell from your id, sorry.

**Comment by whowutwut** [comment]
Doc changes to close out this issue
