### ISSUE TITLE
[FVT]2.12 rmvm -f -p could not work sometimes

### ISSUE THREAD

**Issue by junxiawang** [xcat2/xcat-core#455]
1.download the latest build
2.[root@c910f03fsp03v02 ~]# lsdef -v
lsdef - Version 2.11 (git commit 895ad1fa02cd4a69a35ffd07256ade3ffc6491aa, built Sun Nov 22 15:30:53 EST 2015)
[root@c910f03fsp03v02 ~]# 
3.
[root@c910f03fsp03v02 ~]# rmvm c910f03fsp03v03 -f -p
Error: kvm plugin bug, pid 6020, process description: 'xCATd SSL: rmvm to c910f03fsp03v03 for root@localhost: kvm instance' with error 'libvirt error code: 38, message: cannot unlink file '/var/lib/libvirt/images/c910f03fsp03v03.sda.qcow2': Success
' while trying to fulfill request for the following nodes: c910f03fsp03v03

ssh kvmhost:
[root@node-32030901 ~]# find / -name "c910f03fsp03v03*"
/var/lib/libvirt/images/c910f03fsp03v03.sda.qcow2
---------------------> the file still here

**Comment by whowutwut** [comment]
@zet809  if you are busy, I'd like to give this one to @pdlun92

**Comment by daniceexi** [comment]
In current code logic, the **rmvm -f -p** tried to destory the vm first and then delete the disk. But I am afraid the issue caused by the **destory** action did not finish when calling the delete of disk. We may need to check the power state to be **off** before deleting the disk.

An work around for this issue is, we should use two command to replace **-f -p**

* rpower off the node first
* rmvm -p to delete the vm

**Comment by tingtli** [comment]
Seems it does not work also.
c910f03fsp03v04:~ # rpower c910f03fsp03v05 stat
c910f03fsp03v05: off
c910f03fsp03v04:~ # rmvm c910f03fsp03v05 -f -p
c910f03fsp03v04:~ # mkvm c910f03fsp03v05 -s 20G
c910f03fsp03v05: Error: Storage creation request conflicts with existing file(s)

**Comment by immarvin** [comment]
seems that ``rmvm c910f03fsp03v05 -f -p``  failed to destroy the volume

cannot recreate now

**Comment by daniceexi** [comment]
@immarvin I tried with with following command to replace the rmvmk <node> -f -p, it worked.
~~~~
rpower <node> off
rmvm <node> -p 
~~~~

Could you help FVT to change the current test frame to be following to see whether this is a workaround.
~~~~
rpower <node> off
sleep 10
rmvm <node> -p 
~~~~

**Comment by gurevichmark** [comment]
I am not able to recreate this issue on the April 21 2016 build.
```rmvm <vm> -f -p ``` always deletes the qcow2 file. Tied it with running vm and with vm not running.

Closing the issue. If anyone can find a system where this still does not work, let me know.

**Comment by gurevichmark** [comment]
Re-opening the issue. I can recreate it again.
The error happens when calling  $vol->delete(); from rmvm() in kvm.pm

**Comment by gurevichmark** [comment]
The problem here is really with sys-virt library.
The same error can be produced by going to the kvm host and doing:
virsh destroy (or shutdown) <vm_name>
virsh vol-delete /var/lib/libvirt/images/<vm_name>.sda.qcow2

Waiting several minutes between shutdown and vol-delete does not make a difference.

However, with some experimentation, it appears that doing vol-info after shutdown or destroy fixes the problem and vol-delete then works.

**Comment by gurevichmark** [comment]
Fixed by pull request #1039

**Comment by whowutwut** [comment]
:+1: nice debug @gurevichmark

**Comment by immarvin** [comment]
well done @gurevichmark. 

Since I noticed that this problem cannot be recreated every time during debugging, I think the issue needs a lot of verification test in our autotest env.  @tingtli @daniceexi

**Comment by whowutwut** [comment]
@junxiawang I don't think we can close this issue.  On the midweek interlock @gurevichmark  said that the fix @daniceexi  made does not fix this problem .  I think we need to update the FVT testcase to cover the scenario that Mark has...

**Comment by gurevichmark** [comment]
Hopefully final fix added under pull request #1112 
Based on Xiaopeng's suggestion:

```
Hi Mark,
 
Thanks for the digging.
 
From the RH bugzilla, someone mentioned your workaround that dump the volume definition before the deleting
 operating might help. So with the current retry logic, we can take back the '$vol->get_info();' before the delete 
operation.
```
